name: Build Docker Image
on:
  pull_request:
    branches: [ main]
  push:
    branches: [ main]

# https://docs.github.com/en/actions/quickstart
# https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # need to create an environment variable with org + repo in lowercase not HabitatEnergy
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.*
          check-latest: true

      # 🤓 https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          # fetch-depth: 0
          path: ''

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: latest
          #tags: $REPO:$(date +%s), $REPO:latest

      #- 
      #  name: Build the Docker image
      #  run: docker build . --file Dockerfile --tag ${REPO}:$(date +%s)

      #- uses: actions/checkout@v2
      #  name: Check out code

      #- uses: mr-smithers-excellent/docker-build-push@v5
      #  name: Build & push Docker image
      #  with:
      #    image: $REPO
      #    tags: v1, latest
      #    registry: registry-url.io
      #    dockerfile: Dockerfile.ci
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}

      #-
      #  name: Build and publish image
      #  uses: zmingxie/docker_buildx@master
      #  with:
      #    publish: false
      #    platform: linux/amd64
      #    imageName: ${REPO}

      # 🤓 https://github.com/marketplace/actions/ghcr-docker-buildx-build
      #- name: GHCR Docker Buildx Build
      #  uses: bskiefer/docker_buildx@v1.4

      # 🤓 https://github.com/marketplace/actions/ghcr-action
      #- name: GHCR-Action
      #  uses: KuhlTime/ghcr-action@v1
      #  with:
      #    token: ${{ secrets.GITHUB_TOKEN }}

      #- name: Build Docker Image0
      #  run: |
      #    docker build -t .  
      #- name: Push Docker Image
      #  run: |
      #    echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
      #    docker push ghcr.io/$REPO:$GITHUB_RUN_ID
      # https://github.com/marketplace/actions/push-to-ghcr

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}  # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # optionally push to the Docker Hub (docker.io)
          # docker_io_token: ${{ secrets.DOCKER_IO_ACCESS_TOKEN }}  # see https://hub.docker.com/settings/security
          # customize the username to be used when pushing to the Docker Hub
          # docker_io_user: foobar  # see https://github.com/macbre/push-to-ghcr/issues/14
          
